my_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^my-web/', include('my_web.urls')),
]

my_web/urls.py
from . import views
from django.conf.urls import include, url
from django.conf.urls.static import static



urlpatterns = [
    url(r'^$', views.main),
    url(r'resume/$', views.resume),
    url(r'^register', views.RegisterFormView.as_view()),
    url(r'^login', views.LoginFormView.as_view()),
    url(r'^logout', views.LogoutView.as_view()),
    url(r'^validate-email' , views.validate_email),
    url(r'^add-book/' , views.add_book),
    url(r'^add-author/', views.add_author),
    url(r'^delete/([\d])', views.destroy),
    url(r'^edit/([\d])', views.edit),
    url(r'^update/([\d])', views.update),

]

my_web/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя Фамилия автора') 
    
    def __str__(self):
        return self.name

    
    
class Book(models.Model):
    headline = models.ManyToManyField(Author)
    
    year = models.PositiveIntegerField(verbose_name='Год издания')
    title = models.CharField(max_length=200, verbose_name='Название книги')

    def __str__(self):
        return self.title

    def dict(self):
        obj = {
            'headline': self.headline,
            'year': self.year,
            'title': self.title,
        }
        return obj

my_web/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Author, Book

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name']

my_web/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from .forms import UserCreateForm, BookForm, AuthorForm
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
import json
from django.views.generic.base import View
from django.contrib.auth import logout
from .models import Author, Book
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from django.core.exceptions import ObjectDoesNotExist
from django.db import models



# Create your views here.

def resume(request):
    return render(request, 'resume.html')

class RegisterFormView(FormView):
    form_class = UserCreateForm
    success_url = "/my-web/login"

    template_name = "register.html"

    def form_valid(self , form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)

    def form_invalid(self, form):

        return super(RegisterFormView, self).form_invalid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm

    template_name = "login.html"

    success_url = "/my-web/"

    def form_valid(self, form):
        # Получаем объект пользователя на основе введённых в форму данных.
        self.user = form.get_user()

        # Выполняем аутентификацию пользователя.
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)



class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/my-web/")

def validate_email(request):
    if request.GET:
        email = request.GET.get('email')
        is_taken = User.objects.filter(email=email).exists()
        if is_taken:
            data  = {
                "is_taken" : "На этот почтовый ящик уже зарегистрирован пользователь!"
            }
            return JsonResponse(data)
        else:
            return JsonResponse({'ok': "На этот почтовый адрес не было регистраций"})


def main(request):
    book_form = BookForm
    author_form = AuthorForm
    all_books = Book.objects.all()
    if request.POST:
        query = request.POST['search']
        result_list  = Book.objects.filter(title__contains=query)
        if result_list.count() != 0:
            context = {
                'all_books': all_books,
                'result_list': result_list,
                'query': query,
                'book_form': book_form,
                'author_form': author_form,
            }
        else:
            context ={
                'all_books': all_books,
                'empty': "Совпадений не найдено!",
                'query': query,
            }
    else:
        context ={
                'all_books': all_books,
                'book_form': book_form,
                'author_form': author_form,
                }
    return render(request , 'home.html' , context)


@csrf_exempt
def add_book(request):
    book_form = BookForm
    if request.POST:
        book_form = BookForm(request.POST)
        if book_form.is_valid:
            book_form.save()
            return redirect("/my-web")  
        else:
            book_form = BookForm()
    return redirect("/my-web")


@csrf_exempt
def add_author(request):
    author_form = AuthorForm
    if request.POST:
        author_form = AuthorForm(request.POST)
        if author_form.is_valid:
            author_form.save()
            return redirect("/my-web")  
        else:
            author_form = AuthorForm()
    return redirect("/my-web")


def destroy(request, id):  
    book = Book.objects.get(id=id)  
    book.delete()  
    return redirect("/my-web")


def edit(request, id):  
    book = Book.objects.get(id=id) 
    book_form = BookForm
    ctx = {
        'book': book,
        'book_form': book_form,
        }
        
    return render(request,'edit.html', ctx)

def update(request, id):
    book_form = BookForm
    book = Book.objects.get(id=id)  
    form = BookForm(request.POST, instance = book)  
    if form.is_valid():  
        form.save()  
        return redirect("/my-web")  
    ctx = {
        'book': book,
        'book_form': book_form,
        }
    return render(request, 'edit.html', ctx) 

my_web/templates/edit.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Редактирование</title>
</head>
<body>
    <h1>Форма редактирования</h1>
    <form method="POST" action="/my-web/update/{{book.id}}">
        {% csrf_token %}
        <label>Имя Фамилия автора:</label>
        <div>
            <select name="headline" required id="id_headline" multiple>
                {%for m in book.headline.all%}
                    <option disabled="disabled" style="color: green" selected>{{m}}</option>
                {%endfor%}
                {%for n in book_form.headline%}
                    {{n}}
                {%endfor%}
            </select>
        </div>
        <label>Название книги:</label>
        <div>
            <input type="text" name="title" maxlength="200" required id="id_title" value="{{ book.title }}" />
        </div>
        <label>Год издания:</label>
        <div>
            <input type="number" name="year" min="1900" required id="id_year" value="{{ book.year }}" />
        </div>
        <button type="submit">Редактировать</button>

    </form>

</body>
</html>

my_web/templates/home.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Домашняя страница</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/javascript.js' %}"></script>

</head>
<body>
    <div class="block-login">{% block login %} {% include 'register_part.html' %} {% endblock %} </div>


    <h1 align="center">ДОБРО ПОЖАЛОВАТЬ!</h1>

    <p>Вашему вниманию предлогается список книг.</p>
    <p>
        В случае просмотра данной страницы авторизованным пользователем станут возможными некоторые
        дополнительные функции, а именно: добавление, редактирование, удаление, поиск.

    </p>
    <table border='1' cellpadding="5px">
        <tr style='background-color: darkmagenta; color: white;'>
            <td>ID</td>
            <td>Имя, фамилия автора</td>
            <td>Название книги</td>
            <td>Год издания</td>
            {% if user.is_authenticated %}
            <td></td>
            {% endif %}
        </tr>
        {% for books in all_books %}
        <tr>
            <td>{{books.id}}</td>
            <td>{% for v in books.headline.all %}<li>{{v.name}}</li>{%endfor%}</td>
            <td>{{books.title}}</td>
            <td>{{books.year}}</td>
            {% if user.is_authenticated %}
            <td>
                <a href="/my-web/edit/{{ books.id }}" style="padding: 5px; margin-left:5px">Edit</a>
                <a href="/my-web/delete/{{ books.id }}" style="padding: 5px; margin-left:5px">Delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>


    {% if user.is_authenticated %}
    <br /><br />
    <table border='1' cellpadding="10px">
            <tr style='background-color: blueviolet; color: white;'>
                <td> Добавить книгу</td>
                <td>Добавить автора</td>
                <td>Форма поиска</td>
            </tr><tr>
                     <td>
                         <div>
                             <form id='add-book' action="/my-web/add-book/" method='post' style="display: block; position: relative; left: 10px; top: 10px">
                                 {% csrf_token %}

                                 <label>Автор</label>
                                 <div>{{book_form.headline}}</div>
                                 <label>Название книги</label>
                                 <div>{{book_form.title}}</div>
                                 <label>Год издания</label>
                                 <div>{{book_form.year}}</div>
                                 <button type='submit' style="display: inline">Добавить книгу</button>
                             </form>
                         </div>
                     </td>
                     <td>
                         <div>
                             <form id='add-author' action="/my-web/add-author/" method='post' style="display: block; position: relative; left: 10px; top: 10px">
                                 {% csrf_token %}

                                 <label>Имя Фамилия автора</label>
                                 <div>{{author_form.name}}</div>
                                 <button type='submit' style="display: inline">Добавить автора</button>
                             </form>
                         </div>
                     </td>
                     <td>
                         <div>
                             <form action="" method='post' style="display: block; position: relative; left: 10px; top: 5px">
                             {% csrf_token %}
                             <label for="">Введите название книги: </label>
                             <div>
                                 <input name='search' type="text">
                                 <button style="display: inline">Найти</button>
                             </div>
                             </form>

                         <h4>Результаты поиска по "{{query}}"</h4>

                         {% if empty %}
                         <p style='color: red;'>{{empty}}</p>
                         {% endif %}
                         <table border='1'>
                             <tr style='background-color: blueviolet; color: white;'>
                                 <td>ID</td>
                                 <td>Имя, фамилия автора</td>
                                 <td>Название книги</td>
                                 <td>Год издания</td>
                             </tr>
                             {% for elem in result_list %}
                             <tr>
                                 <td>{{elem.id}}</td>
                                 <td>
                                     {% for v in elem.headline.all %}

                                     <li>{{v.name}}</li>
                                     {%endfor%}
                                 </td>
                                 <td>{{elem.title}}</td>
                                 <td>{{elem.year}}</td>
                             </tr>
                             {% endfor %}
                         </table>
                         </div>
                     </td>
            </tr>
        </table>
   
    {% endif %}

</body>
<footer> <a href="/my-web/resume">  Резюме автора сайта </a></footer>
</html>

my_web/templates/login.html
{% extends 'home.html' %}

{% block login %}
<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
    <label>{{field.label}}</label>
    <p>{{field}}</p>
    {% if field.errors %}
    <p>{{field.errors}}</p>
    {% endif %}
    {% endfor %}
    <button type="submit">Войти</button>
</form>

{% endblock %}

my_web/templates/register.html
{% extends 'home.html' %}

{% block login %}

<form action="" method="post">
    {% csrf_token %}

    {% for field in form %}
    <div class="form-group">

        <label for="">{{field.label}}</label>
        <div>{{field}}</div>
        {% if field.errors %}
        <p>{{field.errors}}</p>
        {% endif %}
        </div>
        {% endfor %}
    <p id='error-mail'></p>


        <button id="btn" type="submit">Зарегистрироваться</button>
</form>
 {% endblock %}

my_web/templates/register_part.html
{% if user.is_authenticated  %}
<a href="logout">Выйти({{user.username}})</a>
{% else %}
<a href="register">Регистрация на сайте</a>
<a href="login">Авторизация</a>
{% endif %}

my_web/templates/resume.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Резюме</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <style>
        ul li {
            line-height: 2;
        }
    </style>
</head>
<body>
    <a href="/my-web">Вернуться на главную</a>
    <div>
        <h1 align="center" style="color: darkblue;font-size: 30pt; text-decoration:underline">РЕЗЮМЕ</h1>
        <img src="{% static 'images/foto.jpg'%}"
             width="200" border="2" style=" border-color: darkblue" align="left" hspace="40" vspace="20" />
        <br />
        <h1>Лисевич Оксана</h1>
        <p>Телефон: 096-128-05-17, 099-77-46-207</p>
        <p>Эл. почта: 417ksenia@gmail.com</p>
        <p>Город: Запорожье</p>
        <p>Возраст: 28 лет</p>
    </div>
    <br />
    <div>
        <h2>Образование</h2>
        <ul>
            <li>
                <b>ITVDN - Python Developer, Django</b> <br />
                online-курсы (11.2018 - наст. время)
            </li>
            <li>
                <b>
                    QATestlab - Основы тестирования ПО </b><br />
                    (11-12.2018)
</li>
            <li>
                <b>ТОВ Адажио - Бухгалтерия, 1С </b><br />
                    (06-08.2016)
</li>
            <li>
                <b>ЗНТУ - Электротехнический ф-т, специальность электрические аппараты </b><br />
                    (09.2007-06.2012)
</li>

        </ul>
        <h2>Опыт работы</h2>
        <ul>
            <li>
                <b>Мастер ногтевого сервиса (на себя)</b><br />
                (02.2014-наст. время)
            </li>
            <li>
                <b>Менеджер, LifePlayer (Обучение построению бизнеса) </b><br />
                (10.2014-01.2015) <br />
                Консультация и телефонные продажи по странам СНГ обучения построению и развитию бизнеса,
                ведение отчетности в CRM
            </li>
            <li>
                <b>Менеджер, Полигон (Подрядная организация Киевстар, подключение к интернету)</b> <br />
                (01.2012-01.2013) <br />
                Телефонная продажа услуг подключения к интернету.
                Повышение до старшего менеджера (помимо продаж, проведение собеседований,
                обучение и контроль работы менеджеров)
                и потом до тренера по продажам
            </li>
        </ul>

    </div>
</body>
</html>